
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app.dart';
import 'firebase_options.dart' as fb_options;

// Initialize Firebase. If `lib/firebase_options.dart` (generated by
// FlutterFire) provides `DefaultFirebaseOptions.currentPlatform`, use
// it. Otherwise fall back to a no-options initialization or log a
// helpful message. The placeholder `firebase_options.dart` in this
// repo returns null for `currentPlatform` so initialization stays safe.
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    final opts = fb_options.DefaultFirebaseOptions.currentPlatform;
    if (opts != null) {
      await Firebase.initializeApp(options: opts);
    } else {
      await Firebase.initializeApp();
    }
  } catch (e) {
    debugPrint('Firebase.initializeApp() failed: $e');
    debugPrint('See .github/copilot-instructions.md for setup instructions.');
  }
  runApp(const ScrapItDownApp());
}
